services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'D:\mongo:/data/db'
#  postgres:
#    image: postgres
#    environment:
#      POSTGRES_USER: sa
#      POSTGRES_PASSWORD: password
#    ports:
#      - '5432:5432'
  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - 'D:\ollama:/root/.ollama'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  cassandra:
    image: cassandra:latest
    ports:
      - '9042:9042'
    volumes:
      - 'D:\cassandra:/var/lib/cassandra'
