spring:
  application:
    name: yelp-analysis


data:
  businessfile: C:\Users\Kirks\IdeaProjects\yelp-analysis\archive\yelp_academic_dataset_business.json
  checkinfile: C:\Users\Kirks\IdeaProjects\yelp-analysis\archive\yelp_academic_dataset_checkin.json
  userfile: C:\Users\Kirks\IdeaProjects\yelp-analysis\archive\yelp_academic_dataset_user.json
  reviewfile: C:\Users\Kirks\IdeaProjects\yelp-analysis\archive\yelp_academic_dataset_review.json



#logging:
#  level:
#    org.springframework.batch.core: DEBUG